### Get semua catatan
GET http://localhost:5000/

### Get catatan berdasarkan ID
GET http://localhost:5000/1

### Tambah catatan
POST http://localhost:5000/
Content-Type: application/json

{
  "judul_Catatan": "Belajar Cloud Computing",
  "deskripsi_Catatan": "Mempelajari konsep dasar Cloud Computing"
}

### Update catatan
PUT http://localhost:5000/1
Content-Type: application/json

{
  "judul_Catatan": "Belajar Cloud Computing dengan baik",
  "deskripsi_Catatan": "Mempelajari konsep dasar Cloud Computing dengan baik"
}

### Hapus catatan
DELETE http://localhost:5000/1

### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "22q1testuser",
  "password": "123456",
  "name": "Test User"
}

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456"
}

### Get Notes (gunakan token yang didapat dari response login di atas)
GET http://localhost:5000/api/notes
//Authorization: Bearer {{TOKEN_HERE}}
